#define _GNU_SOURCE
#include "beancraft/qbe.h"
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <unistd.h>

// ---------------------------------------------------------------------------
// Growable text buffer
// ---------------------------------------------------------------------------

typedef struct {
    char *data;
    size_t len;
    size_t cap;
} QbeBuffer;

static void buf_init(QbeBuffer *buf) {
    buf->cap = 4096;
    buf->data = malloc(buf->cap);
    buf->len = 0;
    buf->data[0] = '\0';
}

static void buf_free(QbeBuffer *buf) {
    free(buf->data);
}

static void buf_ensure(QbeBuffer *buf, size_t need) {
    if (buf->len + need >= buf->cap) {
        while (buf->len + need >= buf->cap) {
            buf->cap *= 2;
        }
        buf->data = realloc(buf->data, buf->cap);
    }
}

static void buf_printf(QbeBuffer *buf, const char *fmt, ...) {
    va_list args;
    va_start(args, fmt);

    va_list args_copy;
    va_copy(args_copy, args);
    int needed = vsnprintf(NULL, 0, fmt, args_copy);
    va_end(args_copy);

    if (needed < 0) {
        va_end(args);
        return;
    }

    buf_ensure(buf, (size_t)needed + 1);
    buf->len += (size_t)vsnprintf(buf->data + buf->len, buf->cap - buf->len, fmt, args);
    va_end(args);
}

static void buf_puts(QbeBuffer *buf, const char *s) {
    size_t len = strlen(s);
    buf_ensure(buf, len + 1);
    memcpy(buf->data + buf->len, s, len + 1);
    buf->len += len;
}

// ---------------------------------------------------------------------------
// Shared QBE fragments (used by both the plain and the optimized backend)
// ---------------------------------------------------------------------------

// Header comment + the global register storage array.
static void emit_header(QbeBuffer *buf, uint32_t reg_count, bool optimized) {
    buf_printf(buf, "# Generated by beancraft-c QBE backend%s\n",
               optimized ? " (optimized)" : "");
    buf_puts(buf, "# Each register is a Bignum (pointer-tagged 64-bit word);\n");
    buf_puts(buf, "# the runtime functions bc_inc/bc_dec/bc_zero/bc_transfer operate on it.\n\n");
    buf_puts(buf, "# Register storage\n");
    buf_printf(buf, "export data $bc_regs = align 8 { z %u }\n\n",
               (unsigned)(reg_count * 8));
}

// Begin the @inst_<i> basic block: bump the step counter and bail to @exit if
// it reached the limit, otherwise fall through to @inst_<i>_body.
static void emit_step_check(QbeBuffer *buf, uint32_t i) {
    buf_printf(buf, "@inst_%u\n", i);
    buf_puts(buf, "    %steps =l add %steps, 1\n");
    buf_puts(buf, "    %limit_check =w cugel %steps, %max_steps\n");
    buf_printf(buf, "    jnz %%limit_check, @exit, @inst_%u_body\n", i);
    buf_printf(buf, "@inst_%u_body\n", i);
}

// Compute %ptr = &bc_regs[reg].
static void emit_reg_ptr(QbeBuffer *buf, const char *name, uint32_t reg) {
    buf_printf(buf, "    %%%s =l add $bc_regs, %u\n", name, reg * 8);
}

// The @exit block and the closing brace of $bc_run.
static void emit_run_footer(QbeBuffer *buf) {
    buf_puts(buf, "@exit\n");
    buf_puts(buf, "    ret %steps\n");
    buf_puts(buf, "}\n\n");
}

// $bc_reg_count plus the register-name table consumed by the driver.
static void emit_reg_metadata(QbeBuffer *buf, Str **reg_names, uint32_t reg_count) {
    buf_puts(buf, "export function l $bc_reg_count() {\n");
    buf_puts(buf, "@start\n");
    buf_printf(buf, "    ret %u\n", reg_count);
    buf_puts(buf, "}\n\n");

    buf_puts(buf, "# Register names\n");
    for (uint32_t i = 0; i < reg_count; i++) {
        buf_printf(buf, "data $bc_regname_%u = { b \"", i);
        for (const char *p = reg_names[i]->data; *p; p++) {
            if (*p == '"' || *p == '\\') {
                buf_printf(buf, "\\%c", *p);
            } else {
                char s[2] = { *p, '\0' };
                buf_puts(buf, s);
            }
        }
        buf_puts(buf, "\", b 0 }\n");
    }
    buf_puts(buf, "\n");

    buf_puts(buf, "export data $bc_reg_names = align 8 {\n");
    for (uint32_t i = 0; i < reg_count; i++) {
        buf_printf(buf, "    l $bc_regname_%u%s\n", i, i + 1 < reg_count ? "," : "");
    }
    buf_puts(buf, "}\n\n");
}

// $bc_set_reg / $bc_get_reg: a 64-bit numeric view of a register, kept for
// callers that want one without going through the bignum runtime.
static void emit_reg_accessors(QbeBuffer *buf) {
    buf_puts(buf, "# Set a register to a small immediate by index\n");
    buf_puts(buf, "export function $bc_set_reg(l %idx, l %value) {\n");
    buf_puts(buf, "@start\n");
    buf_puts(buf, "    %offset =l mul %idx, 8\n");
    buf_puts(buf, "    %ptr =l add $bc_regs, %offset\n");
    buf_puts(buf, "    %shifted =l shl %value, 1\n");
    buf_puts(buf, "    %tagged =l or %shifted, 1\n");
    buf_puts(buf, "    storel %tagged, %ptr\n");
    buf_puts(buf, "    ret\n");
    buf_puts(buf, "}\n\n");

    buf_puts(buf, "# Read a register by index (exact value if it fits in 64 bits)\n");
    buf_puts(buf, "export function l $bc_get_reg(l %idx) {\n");
    buf_puts(buf, "@start\n");
    buf_puts(buf, "    %offset =l mul %idx, 8\n");
    buf_puts(buf, "    %ptr =l add $bc_regs, %offset\n");
    buf_puts(buf, "    %tagged =l loadl %ptr\n");
    buf_puts(buf, "    %is_imm =l and %tagged, 1\n");
    buf_puts(buf, "    jnz %is_imm, @immediate, @heap\n");
    buf_puts(buf, "@immediate\n");
    buf_puts(buf, "    %value =l shr %tagged, 1\n");
    buf_puts(buf, "    ret %value\n");
    buf_puts(buf, "@heap\n");
    buf_puts(buf, "    %val =l call $bc_bignum_to_u64(l %tagged)\n");
    buf_puts(buf, "    ret %val\n");
    buf_puts(buf, "}\n\n");
}

// ---------------------------------------------------------------------------
// Backends
// ---------------------------------------------------------------------------

BcResult qbe_generate(FILE *out, const IrProgram *prog, QbeOptions opts) {
    QbeBuffer buf;
    buf_init(&buf);

    emit_header(&buf, prog->reg_count, false);

    buf_puts(&buf, "# Run the program; returns the number of steps executed.\n");
    buf_puts(&buf, "export function l $bc_run(l %max_steps) {\n");
    buf_puts(&buf, "@entry\n");
    buf_puts(&buf, "    %steps =l copy 0\n");
    buf_puts(&buf, "    jmp @inst_0\n\n");

    for (uint32_t i = 0; i < prog->inst_count; i++) {
        const IrInst *inst = &prog->insts[i];

        if (opts.emit_debug_info && prog->label_names && prog->label_names[i]) {
            buf_printf(&buf, "# %s\n", prog->label_names[i]->data);
        }
        emit_step_check(&buf, i);

        switch (inst->op) {
        case IR_INC:
            emit_reg_ptr(&buf, "ptr", inst->reg);
            buf_puts(&buf, "    call $bc_inc(l %ptr)\n");
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;
        case IR_DEB:
            emit_reg_ptr(&buf, "ptr", inst->reg);
            buf_puts(&buf, "    %was_positive =w call $bc_dec(l %ptr)\n");
            buf_printf(&buf, "    jnz %%was_positive, @inst_%u, @inst_%u\n\n",
                       inst->arg_b, inst->arg_a);
            break;
        case IR_END:
            buf_puts(&buf, "    jmp @exit\n\n");
            break;
        }
    }

    emit_run_footer(&buf);
    emit_reg_accessors(&buf);
    emit_reg_metadata(&buf, prog->reg_names, prog->reg_count);

    fputs(buf.data, out);
    buf_free(&buf);
    return BC_OK(NULL);
}

BcResult qbe_generate_opt(FILE *out, const IrOptProgram *prog, QbeOptions opts) {
    QbeBuffer buf;
    buf_init(&buf);

    emit_header(&buf, prog->reg_count, true);

    buf_puts(&buf, "# Run the program; returns the number of steps executed.\n");
    buf_puts(&buf, "export function l $bc_run(l %max_steps) {\n");
    buf_puts(&buf, "@entry\n");
    buf_puts(&buf, "    %steps =l copy 0\n");
    buf_puts(&buf, "    jmp @inst_0\n\n");

    for (uint32_t i = 0; i < prog->inst_count; i++) {
        const IrOptInst *inst = &prog->insts[i];
        emit_step_check(&buf, i);

        switch (inst->op) {
        case IR_OPT_INC:
            emit_reg_ptr(&buf, "ptr", inst->reg);
            buf_puts(&buf, "    call $bc_inc(l %ptr)\n");
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;

        case IR_OPT_DEB:
            emit_reg_ptr(&buf, "ptr", inst->reg);
            buf_puts(&buf, "    %was_positive =w call $bc_dec(l %ptr)\n");
            buf_printf(&buf, "    jnz %%was_positive, @inst_%u, @inst_%u\n\n",
                       inst->arg_b, inst->arg_a);
            break;

        case IR_OPT_END:
            buf_puts(&buf, "    jmp @exit\n\n");
            break;

        case IR_OPT_ZERO:
            if (opts.emit_debug_info)
                buf_printf(&buf, "    # ZERO %s\n", prog->reg_names[inst->reg]->data);
            emit_reg_ptr(&buf, "ptr", inst->reg);
            buf_puts(&buf, "    call $bc_zero(l %ptr)\n");
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;

        case IR_OPT_TRANSFER:
            if (opts.emit_debug_info) {
                buf_printf(&buf, "    # TRANSFER %s -> {", prog->reg_names[inst->reg]->data);
                for (uint32_t d = 0; d < inst->dest_count; d++)
                    buf_printf(&buf, "%s%s", d ? ", " : "",
                               prog->reg_names[prog->dests[inst->dest_off + d]]->data);
                buf_puts(&buf, "}\n");
            }
            emit_reg_ptr(&buf, "src", inst->reg);
            buf_puts(&buf, "    %srcval =l loadl %src\n");
            for (uint32_t d = 0; d < inst->dest_count; d++) {
                buf_printf(&buf, "    %%dst%u =l add $bc_regs, %u\n",
                           d, prog->dests[inst->dest_off + d] * 8);
                buf_printf(&buf, "    call $bc_add_into(l %%dst%u, l %%srcval)\n", d);
            }
            buf_puts(&buf, "    call $bc_zero(l %src)\n");
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;

        case IR_OPT_COPY:
            // The optimizer never emits COPY; if it ever does, fall through
            // harmlessly rather than miscompile.
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;

        default:
            buf_printf(&buf, "    # unknown op %d\n", inst->op);
            buf_puts(&buf, "    jmp @exit\n\n");
            break;
        }
    }

    emit_run_footer(&buf);
    emit_reg_accessors(&buf);
    emit_reg_metadata(&buf, prog->reg_names, prog->reg_count);

    fputs(buf.data, out);
    buf_free(&buf);
    return BC_OK(NULL);
}

BcResult qbe_generate_string(char **out, const IrProgram *prog, QbeOptions opts) {
    char *buf = NULL;
    size_t size = 0;
    FILE *stream = open_memstream(&buf, &size);
    if (!stream) {
        *out = NULL;
        return BC_OK(NULL);
    }

    BcResult result = qbe_generate(stream, prog, opts);
    fclose(stream);

    if (result.ok) {
        *out = buf;
    } else {
        free(buf);
        *out = NULL;
    }
    return result;
}

int qbe_compile(const char *qbe_source, const char *output_path) {
    char temp_path[] = "/tmp/beancraft_XXXXXX.ssa";
    int fd = mkstemps(temp_path, 4);
    if (fd < 0) return -1;

    FILE *f = fdopen(fd, "w");
    if (!f) {
        close(fd);
        return -1;
    }
    fputs(qbe_source, f);
    fclose(f);

    char asm_path[256];
    snprintf(asm_path, sizeof(asm_path), "%s.s", output_path);

    char cmd[512];
    snprintf(cmd, sizeof(cmd), "qbe -o %s %s", asm_path, temp_path);
    int ret = system(cmd);
    unlink(temp_path);
    if (ret != 0) return -1;

    snprintf(cmd, sizeof(cmd), "cc -c -o %s %s", output_path, asm_path);
    ret = system(cmd);
    unlink(asm_path);
    return ret == 0 ? 0 : -1;
}

int qbe_link(const char *object_path, const char *output_path) {
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "cc -o %s %s -L. -lbcruntime", output_path, object_path);
    return system(cmd) == 0 ? 0 : -1;
}
