#define _GNU_SOURCE
#include "beancraft/qbe.h"
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <unistd.h>

// Buffer for building QBE output
typedef struct {
    char *data;
    size_t len;
    size_t cap;
} QbeBuffer;

static void buf_init(QbeBuffer *buf) {
    buf->cap = 4096;
    buf->data = malloc(buf->cap);
    buf->len = 0;
    buf->data[0] = '\0';
}

static void buf_free(QbeBuffer *buf) {
    free(buf->data);
}

static void buf_ensure(QbeBuffer *buf, size_t need) {
    if (buf->len + need >= buf->cap) {
        while (buf->len + need >= buf->cap) {
            buf->cap *= 2;
        }
        buf->data = realloc(buf->data, buf->cap);
    }
}

static void buf_printf(QbeBuffer *buf, const char *fmt, ...) {
    va_list args;
    va_start(args, fmt);

    // First, determine how much space we need
    va_list args_copy;
    va_copy(args_copy, args);
    int needed = vsnprintf(NULL, 0, fmt, args_copy);
    va_end(args_copy);

    buf_ensure(buf, needed + 1);

    buf->len += vsnprintf(buf->data + buf->len, buf->cap - buf->len, fmt, args);
    va_end(args);
}

static void buf_puts(QbeBuffer *buf, const char *s) {
    size_t len = strlen(s);
    buf_ensure(buf, len + 1);
    memcpy(buf->data + buf->len, s, len + 1);
    buf->len += len;
}

// Generate a valid QBE identifier from a register name
// Replaces special characters with underscores
static void emit_reg_name(QbeBuffer *buf, const char *name) {
    buf_puts(buf, "reg_");
    for (const char *p = name; *p; p++) {
        char c = *p;
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') || c == '_') {
            char s[2] = {c, '\0'};
            buf_puts(buf, s);
        } else {
            buf_puts(buf, "_");
        }
    }
}

BcResult qbe_generate(FILE *out, const IrProgram *prog, QbeOptions opts) {
    QbeBuffer buf;
    buf_init(&buf);

    // Header comment
    buf_puts(&buf, "# Generated by beancraft-c QBE backend\n");
    buf_puts(&buf, "# Registers are stored as Bignum values (uint64_t with pointer tagging)\n\n");

    // Declare external runtime functions
    buf_puts(&buf, "# External runtime functions\n");
    buf_puts(&buf, "# void bc_inc(uint64_t *reg) - increment register\n");
    buf_puts(&buf, "# int bc_dec(uint64_t *reg) - decrement register, returns 1 if was positive\n\n");

    // Data section: register storage
    // We use a global array to store registers
    buf_puts(&buf, "# Register storage\n");
    buf_printf(&buf, "export data $bc_regs = align 8 { z %u }\n\n",
               (unsigned)(prog->reg_count * 8));

    // Generate the main execution function
    buf_puts(&buf, "# Main execution function\n");
    buf_puts(&buf, "# Returns number of steps executed\n");
    buf_puts(&buf, "export function l $bc_run(l %max_steps) {\n");

    // Entry block - initialize step counter
    buf_puts(&buf, "@entry\n");
    buf_puts(&buf, "    %steps =l copy 0\n");
    buf_puts(&buf, "    jmp @inst_0\n\n");

    // Generate a basic block for each instruction
    for (uint32_t i = 0; i < prog->inst_count; i++) {
        const IrInst *inst = &prog->insts[i];

        // Block label with optional debug comment
        if (opts.emit_debug_info && prog->label_names && prog->label_names[i]) {
            buf_printf(&buf, "@inst_%u  # %s\n", i, prog->label_names[i]->data);
        } else {
            buf_printf(&buf, "@inst_%u\n", i);
        }

        // Check step limit
        buf_puts(&buf, "    %steps =l add %steps, 1\n");
        buf_puts(&buf, "    %limit_check =w cugel %steps, %max_steps\n");
        buf_puts(&buf, "    jnz %limit_check, @exit, @inst_");
        buf_printf(&buf, "%u_body\n", i);

        buf_printf(&buf, "@inst_%u_body\n", i);

        switch (inst->op) {
        case IR_INC: {
            // Increment register and jump to next
            buf_printf(&buf, "    %%ptr =l add $bc_regs, %u\n", inst->reg * 8);
            buf_puts(&buf, "    call $bc_inc(l %ptr)\n");
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;
        }

        case IR_DEB: {
            // Decrement register and branch based on result
            buf_printf(&buf, "    %%ptr =l add $bc_regs, %u\n", inst->reg * 8);
            buf_puts(&buf, "    %was_positive =w call $bc_dec(l %ptr)\n");
            buf_printf(&buf, "    jnz %%was_positive, @inst_%u, @inst_%u\n\n",
                      inst->arg_b, inst->arg_a);
            break;
        }

        case IR_END:
            buf_puts(&buf, "    jmp @exit\n\n");
            break;
        }
    }

    // Exit block
    buf_puts(&buf, "@exit\n");
    buf_puts(&buf, "    ret %steps\n");
    buf_puts(&buf, "}\n\n");

    // Generate initialization function
    buf_puts(&buf, "# Initialize a register by index\n");
    buf_puts(&buf, "export function $bc_set_reg(l %idx, l %value) {\n");
    buf_puts(&buf, "@start\n");
    buf_puts(&buf, "    %offset =l mul %idx, 8\n");
    buf_puts(&buf, "    %ptr =l add $bc_regs, %offset\n");
    buf_puts(&buf, "    # Convert value to tagged immediate: (value << 1) | 1\n");
    buf_puts(&buf, "    %shifted =l shl %value, 1\n");
    buf_puts(&buf, "    %tagged =l or %shifted, 1\n");
    buf_puts(&buf, "    storel %tagged, %ptr\n");
    buf_puts(&buf, "    ret\n");
    buf_puts(&buf, "}\n\n");

    // Generate register read function
    buf_puts(&buf, "# Read a register by index (returns untagged value or 0 if heap)\n");
    buf_puts(&buf, "export function l $bc_get_reg(l %idx) {\n");
    buf_puts(&buf, "@start\n");
    buf_puts(&buf, "    %offset =l mul %idx, 8\n");
    buf_puts(&buf, "    %ptr =l add $bc_regs, %offset\n");
    buf_puts(&buf, "    %tagged =l loadl %ptr\n");
    buf_puts(&buf, "    %is_imm =l and %tagged, 1\n");
    buf_puts(&buf, "    jnz %is_imm, @immediate, @heap\n");
    buf_puts(&buf, "@immediate\n");
    buf_puts(&buf, "    %value =l shr %tagged, 1\n");
    buf_puts(&buf, "    ret %value\n");
    buf_puts(&buf, "@heap\n");
    buf_puts(&buf, "    # For heap values, call runtime to convert\n");
    buf_puts(&buf, "    %val =l call $bc_bignum_to_u64(l %tagged)\n");
    buf_puts(&buf, "    ret %val\n");
    buf_puts(&buf, "}\n\n");

    // Generate register count accessor
    buf_printf(&buf, "export function l $bc_reg_count() {\n");
    buf_puts(&buf, "@start\n");
    buf_printf(&buf, "    ret %u\n", prog->reg_count);
    buf_puts(&buf, "}\n\n");

    // Generate register name table (as null-terminated strings)
    buf_puts(&buf, "# Register names\n");
    for (uint32_t i = 0; i < prog->reg_count; i++) {
        const char *name = prog->reg_names[i]->data;
        buf_printf(&buf, "data $bc_regname_%u = { b \"", i);
        // Escape the string for QBE
        for (const char *p = name; *p; p++) {
            if (*p == '"' || *p == '\\') {
                buf_printf(&buf, "\\%c", *p);
            } else {
                char s[2] = {*p, '\0'};
                buf_puts(&buf, s);
            }
        }
        buf_puts(&buf, "\", b 0 }\n");
    }
    buf_puts(&buf, "\n");

    // Generate pointer array to names
    buf_puts(&buf, "export data $bc_reg_names = align 8 {\n");
    for (uint32_t i = 0; i < prog->reg_count; i++) {
        buf_printf(&buf, "    l $bc_regname_%u", i);
        if (i < prog->reg_count - 1) {
            buf_puts(&buf, ",");
        }
        buf_puts(&buf, "\n");
    }
    buf_puts(&buf, "}\n\n");

    // Write to file
    fputs(buf.data, out);

    buf_free(&buf);
    return BC_OK(NULL);
}

// Generate QBE IL from optimized IR
BcResult qbe_generate_opt(FILE *out, const IrOptProgram *prog, QbeOptions opts) {
    QbeBuffer buf;
    buf_init(&buf);

    // Header comment
    buf_puts(&buf, "# Generated by beancraft-c QBE backend (OPTIMIZED)\n");
    buf_puts(&buf, "# Registers are stored as Bignum values (uint64_t with pointer tagging)\n\n");

    // Declare external runtime functions
    buf_puts(&buf, "# External runtime functions\n");
    buf_puts(&buf, "# void bc_inc(uint64_t *reg) - increment register\n");
    buf_puts(&buf, "# int bc_dec(uint64_t *reg) - decrement, returns 1 if was positive\n");
    buf_puts(&buf, "# void bc_zero(uint64_t *reg) - set register to zero\n");
    buf_puts(&buf, "# void bc_transfer(uint64_t *src, uint64_t *dst) - dst += src; src = 0\n\n");

    // Data section: register storage
    buf_puts(&buf, "# Register storage\n");
    buf_printf(&buf, "export data $bc_regs = align 8 { z %u }\n\n",
               (unsigned)(prog->reg_count * 8));

    // Generate the main execution function
    buf_puts(&buf, "# Main execution function (optimized)\n");
    buf_puts(&buf, "export function l $bc_run(l %max_steps) {\n");

    // Entry block
    buf_puts(&buf, "@entry\n");
    buf_puts(&buf, "    %steps =l copy 0\n");
    buf_puts(&buf, "    jmp @inst_0\n\n");

    // Generate a basic block for each instruction
    for (uint32_t i = 0; i < prog->inst_count; i++) {
        const IrOptInst *inst = &prog->insts[i];

        buf_printf(&buf, "@inst_%u\n", i);

        // Step counter (optimized ops count as 1 step)
        buf_puts(&buf, "    %steps =l add %steps, 1\n");
        buf_puts(&buf, "    %limit_check =w cugel %steps, %max_steps\n");
        buf_printf(&buf, "    jnz %%limit_check, @exit, @inst_%u_body\n", i);
        buf_printf(&buf, "@inst_%u_body\n", i);

        switch (inst->op) {
        case IR_OPT_INC:
            buf_printf(&buf, "    %%ptr =l add $bc_regs, %u\n", inst->reg * 8);
            buf_puts(&buf, "    call $bc_inc(l %ptr)\n");
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;

        case IR_OPT_DEB:
            buf_printf(&buf, "    %%ptr =l add $bc_regs, %u\n", inst->reg * 8);
            buf_puts(&buf, "    %was_positive =w call $bc_dec(l %ptr)\n");
            buf_printf(&buf, "    jnz %%was_positive, @inst_%u, @inst_%u\n\n",
                      inst->arg_b, inst->arg_a);
            break;

        case IR_OPT_END:
            buf_puts(&buf, "    jmp @exit\n\n");
            break;

        case IR_OPT_ZERO:
            // O(1) zero operation
            if (opts.emit_debug_info) {
                buf_printf(&buf, "    # ZERO %s\n", prog->reg_names[inst->reg]->data);
            }
            buf_printf(&buf, "    %%ptr =l add $bc_regs, %u\n", inst->reg * 8);
            buf_puts(&buf, "    call $bc_zero(l %ptr)\n");
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;

        case IR_OPT_TRANSFER:
            // O(1) transfer: dst += src; src = 0
            if (opts.emit_debug_info) {
                buf_printf(&buf, "    # TRANSFER %s -> %s\n",
                          prog->reg_names[inst->reg]->data,
                          prog->reg_names[inst->reg2]->data);
            }
            buf_printf(&buf, "    %%src =l add $bc_regs, %u\n", inst->reg * 8);
            buf_printf(&buf, "    %%dst =l add $bc_regs, %u\n", inst->reg2 * 8);
            buf_puts(&buf, "    call $bc_transfer(l %src, l %dst)\n");
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;

        case IR_OPT_COPY:
            // For now, COPY is not implemented - fall back to transfer semantics
            // A true COPY would need: dst = src (non-destructive)
            if (opts.emit_debug_info) {
                buf_printf(&buf, "    # COPY %s -> %s (not yet optimized)\n",
                          prog->reg_names[inst->reg]->data,
                          prog->reg_names[inst->reg2]->data);
            }
            // TODO: implement bc_copy runtime function
            buf_printf(&buf, "    jmp @inst_%u\n\n", inst->arg_a);
            break;

        default:
            buf_printf(&buf, "    # UNKNOWN OP %d\n", inst->op);
            buf_puts(&buf, "    jmp @exit\n\n");
            break;
        }
    }

    // Exit block
    buf_puts(&buf, "@exit\n");
    buf_puts(&buf, "    ret %steps\n");
    buf_puts(&buf, "}\n\n");

    // Generate helper functions (same as non-optimized)
    buf_puts(&buf, "# Initialize a register by index\n");
    buf_puts(&buf, "export function $bc_set_reg(l %idx, l %value) {\n");
    buf_puts(&buf, "@start\n");
    buf_puts(&buf, "    %offset =l mul %idx, 8\n");
    buf_puts(&buf, "    %ptr =l add $bc_regs, %offset\n");
    buf_puts(&buf, "    %shifted =l shl %value, 1\n");
    buf_puts(&buf, "    %tagged =l or %shifted, 1\n");
    buf_puts(&buf, "    storel %tagged, %ptr\n");
    buf_puts(&buf, "    ret\n");
    buf_puts(&buf, "}\n\n");

    buf_puts(&buf, "# Read a register by index\n");
    buf_puts(&buf, "export function l $bc_get_reg(l %idx) {\n");
    buf_puts(&buf, "@start\n");
    buf_puts(&buf, "    %offset =l mul %idx, 8\n");
    buf_puts(&buf, "    %ptr =l add $bc_regs, %offset\n");
    buf_puts(&buf, "    %tagged =l loadl %ptr\n");
    buf_puts(&buf, "    %is_imm =l and %tagged, 1\n");
    buf_puts(&buf, "    jnz %is_imm, @immediate, @heap\n");
    buf_puts(&buf, "@immediate\n");
    buf_puts(&buf, "    %value =l shr %tagged, 1\n");
    buf_puts(&buf, "    ret %value\n");
    buf_puts(&buf, "@heap\n");
    buf_puts(&buf, "    %val =l call $bc_bignum_to_u64(l %tagged)\n");
    buf_puts(&buf, "    ret %val\n");
    buf_puts(&buf, "}\n\n");

    buf_printf(&buf, "export function l $bc_reg_count() {\n");
    buf_puts(&buf, "@start\n");
    buf_printf(&buf, "    ret %u\n", prog->reg_count);
    buf_puts(&buf, "}\n\n");

    // Register name table
    buf_puts(&buf, "# Register names\n");
    for (uint32_t i = 0; i < prog->reg_count; i++) {
        const char *name = prog->reg_names[i]->data;
        buf_printf(&buf, "data $bc_regname_%u = { b \"", i);
        for (const char *p = name; *p; p++) {
            if (*p == '"' || *p == '\\') {
                buf_printf(&buf, "\\%c", *p);
            } else {
                char s[2] = {*p, '\0'};
                buf_puts(&buf, s);
            }
        }
        buf_puts(&buf, "\", b 0 }\n");
    }
    buf_puts(&buf, "\n");

    buf_puts(&buf, "export data $bc_reg_names = align 8 {\n");
    for (uint32_t i = 0; i < prog->reg_count; i++) {
        buf_printf(&buf, "    l $bc_regname_%u", i);
        if (i < prog->reg_count - 1) {
            buf_puts(&buf, ",");
        }
        buf_puts(&buf, "\n");
    }
    buf_puts(&buf, "}\n\n");

    fputs(buf.data, out);
    buf_free(&buf);
    return BC_OK(NULL);
}

BcResult qbe_generate_string(char **out, const IrProgram *prog, QbeOptions opts) {
    // Create a memory stream
    char *buf = NULL;
    size_t size = 0;
    FILE *stream = open_memstream(&buf, &size);
    if (!stream) {
        *out = NULL;
        return BC_OK(NULL); // Could return an error, but keeping it simple
    }

    BcResult result = qbe_generate(stream, prog, opts);
    fclose(stream);

    if (result.ok) {
        *out = buf;
    } else {
        free(buf);
        *out = NULL;
    }

    return result;
}

int qbe_compile(const char *qbe_source, const char *output_path) {
    // Write QBE source to temp file
    char temp_path[] = "/tmp/beancraft_XXXXXX.ssa";
    int fd = mkstemps(temp_path, 4);
    if (fd < 0) return -1;

    FILE *f = fdopen(fd, "w");
    if (!f) {
        close(fd);
        return -1;
    }
    fputs(qbe_source, f);
    fclose(f);

    // Run QBE to generate assembly
    char asm_path[256];
    snprintf(asm_path, sizeof(asm_path), "%s.s", output_path);

    char cmd[512];
    snprintf(cmd, sizeof(cmd), "qbe -o %s %s", asm_path, temp_path);
    int ret = system(cmd);
    unlink(temp_path);

    if (ret != 0) return -1;

    // Assemble to object file
    snprintf(cmd, sizeof(cmd), "cc -c -o %s %s", output_path, asm_path);
    ret = system(cmd);
    unlink(asm_path);

    return ret == 0 ? 0 : -1;
}

int qbe_link(const char *object_path, const char *output_path) {
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "cc -o %s %s -L. -lbcruntime", output_path, object_path);
    return system(cmd) == 0 ? 0 : -1;
}
